### ISSUE TITLE
form has no save method

### ISSUE THREAD

**Issue by branch-git** [branch-git/TTimes#1]
form inherits StaffAttendanceForm in `views.attendanceview`, but `form.save(commit=False)` fails.
I prepared this issue as new branch "save method".

[Preconditions]
1. Run server in local env and access to `127.0.0.1:8000/attendance`

[How to reproduce]
1. Select someone and push button "出勤"

[Actual behavior]
1. Error occurs with save method
 * please refer to [Additional Info.] for detail such as error script.

[Expected behavior]
1. Error does not occur
2. The `attendanceview` succeeds and the data is saved in the database.

[Additional Info.]
Error codes;
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/attendance/

Django Version: 3.1.7
Python Version: 3.8.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'TTimes.apps.TtimesConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "c:\Users\USER_NAME\Desktop\develop\django\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\Users\USER_NAME\Desktop\develop\django\.venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER_NAME\Desktop\develop\django\timecardproject\TTimes\views.py", line 65, in attendanceview
    form.save(commit=False)

Exception Type: AttributeError at /attendance/
Exception Value: 'StaffAttendanceForm' object has no attribute 'save'
```

**Comment by branch-git** [comment]
I inherited `forms.Form` in `forms.StaffAttendanceForm`.
It should have inherited `forms.ModelForm` correctly.

```
# diff at TTimes.forms.py
- class StaffAttendanceForm(forms.From):
+ class StaffAttendanceForm(forms.ModelFrom): 
```

After the above correction, the error has been recovered, so this ticket will be closed as "fixed" and the branch "save method" is deleted.
